### ISSUE TITLE
Use the Go compiler at tip?

### ISSUE THREAD

**Issue by justinclift** [agnivade/shimmer#2]
The README currently has:

> Use the Go compiler at tip.

Is that still correct even with the 1.11 Go release?

Asking because shimmer would probably be a decent example to add to the [WebAssembly wiki](https://github.com/golang/go/wiki/WebAssembly) page. :smile:

**Comment by agnivade** [comment]
Haha no, 1.11 works just fine now.

**Comment by justinclift** [comment]
Thanks, will add this to the examples then. :smile:

**Comment by justinclift** [comment]
Just had a thought.  Any interest in adjusting the Settings -> Source bit for this repo, so it's served via GitHub Pages?

That would allow for linking both to a live demo + to the source.  eg like the ones here:

&nbsp; &nbsp; https://github.com/golang/go/wiki/WebAssembly#webgl-canvas-3d

Seems to be an effective approach. :grin:

**Comment by agnivade** [comment]
Ah no, that won't work because I don't have the compiled shimmer.wasm checked in. But that is a genius idea actually. Maybe I will do it in a separate branch.

**Comment by justinclift** [comment]
Awesome.  Yeah, just add the .wasm + support bits and it should be good to go. :smile:

**Comment by justinclift** [comment]
Added Shimmer to the examples list here:

&nbsp; &nbsp; https://github.com/golang/go/wiki/WebAssembly#general

If/when you get the .wasm file added + GitHub Pages going, feel free to update the entry. :smile:
